from __future__ import annotations
from typing import Any, Dict, List, Protocol, runtime_checkable
Result = Dict[str, Any]

@runtime_checkable
class VectorBackend(Protocol):
    def load(self, cfg: Any) -> None: ...
    def encode(self, text_or_list: Any) -> Any: ...
    def search(self, qvec: Any, top_k: int = 5, filter_source: str | None = None) -> List[Result]: ...
    def close(self) -> None: ...
